export enum GameRoomState {
    WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
    WAITING_TO_START = 'WAITING_TO_START',
    WAITING_FOR_QUESTIONS = 'WAITING_FOR_QUESTIONS',
    WAITING_FOR_ANSWERS = 'WAITING_FOR_ANSWERS',
    ROUND_ENDED = 'ROUND_ENDED',
    ENDED = 'ENDED',
}
