#!/bin/bash

# Problem
# Calculate the average of the PIDs of the processes currently running in the system.

# Expected output
# 8373.95

cat ps.fake | sed -rn "s/^(\S+\s+)([0-9]+).+$/\2/gp;d" | awk 'BEGIN { total = 0; } { total += $1; } END { print total / NR; }'
