#!/bin/bash

# Problem
# Find all the users that logged into the system after 11PM.

# Expected output
# piir1546
# srir1568
# tnir1590
# vlir1593

cat last.fake | sed -rn "s/^([a-z]{4,4}[0-9]{4,4}).+[0-9]+ 23:[0-9]{2}.+/\1/gp;d" | sort | uniq
